#!/usr/bin/env zsh
#
# Inspired by Matthew Denner's dotfiles setup: https://github.com/mattdenner/dotfiles
#

DOTFILES_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "Configuring ZSH  ..."
[[ ! -d ~/.zplug ]] && git clone https://github.com/zplug/zplug ~/.zplug
setopt EXTENDED_GLOB
for rcfile in zshrc zshenv ; do ln -sf ${DOTFILES_DIR}/zsh/${rcfile} ~/.${rcfile} ; done


echo "Configuring development settings ..."
echo "... git"
ln -sf ${DOTFILES_DIR}/git/gitconfig ~/.gitconfig
ln -sf ${DOTFILES_DIR}/git/gitignore ~/.gitignore

echo "... haskell"
mkdir -p ~/.stack/
ln -sf ${DOTFILES_DIR}/development/stack/config.yaml ~/.stack/config.yaml

#echo "... go"
#export GOPATH=${HOME}/Development/golang
#mkdir -p ${GOPATH}

#echo "... vim"
#[[ ! -f ~/.vim/autoload/plug.vim ]] && curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim 2> /dev/null
#ln -sf ${DOTFILES_DIR}/vim/vimrc ~/.vimrc
#ln -sf ${DOTFILES_DIR}/vim/bundles ~/.vimrc.bundles


#echo "... neovim"
#mkdir -p ~/.config/nvim
#ln -sf ${DOTFILES_DIR}/neovim/init.vim ~/.config/nvim/init.vim
#ln -sf ${DOTFILES_DIR}/neovim/config ~/.config/nvim

[[ ! -f /usr/local/bin/brew ]] && /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
(brew tap homebrew/bundle > /dev/null) || (brew tap Homebrew/bundle)

