#!/usr/bin/env zsh
#
# Inspired by Matthew Denner's dotfiles setup: https://github.com/mattdenner/dotfiles
#

DOTFILES_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "Configuring ZSH  ..."

[[ ! -d ~/.zprezto ]] && git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}" 2> /dev/null ; done
for rcfile in zpreztorc zshenv zshrc inputrc zprofile ; do ln -sf ${DOTFILES_DIR}/zsh/${rcfile} ~/.${rcfile} ; done


echo "Configuring development settings ..."
echo "... git"
cp -n ${DOTFILES_DIR}/git/gitconfig ~/.gitconfig
cp -n ${DOTFILES_DIR}/git/gitignore ~/.gitignore

echo "... haskell"
mkdir -p ~/.stack/
ln -sf ${DOTFILES}/development/stack/config.yaml ~/.stack/config.yaml

echo "... go"
export GOPATH=${HOME}/Development/golang
mkdir -p ${GOPATH}

echo "... vim"
[[ ! -f ~/.vim/autoload/plug.vim ]] && curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim 2> /dev/null
ln -sf ${DOTFILES_DIR}/vim/vimrc ~/.vimrc
ln -sf ${DOTFILES_DIR}/vim/bundles ~/.vimrc.bundles


echo "... neovim"
mkdir -p ~/.config/nvim
[[ ! -f ~/.local/share/nvim/site/autoload/plug.vim ]] && curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
ln -sf ${DOTFILES_DIR}/neovim/init.vim ~/.config/nvim/init.vim

[[ ! -f /usr/local/bin/brew ]] && /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
(brew tap caskroom/cask > /dev/null) || (brew tap caskroom/cask && rehash)
(brew cask list iterm2 > /dev/null) || (brew cask install iterm2)
(brew cask list spectacle > /dev/null) || (brew cask install spectacle)
(brew cask list flux > /dev/null) || (brew cask install flux)
(brew tap homebrew/bundle > /dev/null) || (brew tap Homebrew/bundle)

