 set nocompatible               " be iMproved
 filetype off                   " required!
 syntax on
 set encoding=utf-8
 set showcmd
 
 set rtp+=~/.vim/bundle/vundle/
 call vundle#rc()

 " let Vundle manage Vundle
 " required! 
 Bundle 'gmarik/vundle'

 " Jens's additions:
 set rtp+=~/.dotfiles/powerline/repo/powerline/bindings/vim
 "Bundle 'scrooloose/syntastic'
 Bundle 'altercation/vim-colors-solarized'
 Bundle 'Valloric/YouCompleteMe'

 "" Whitespace, tabs etc
 set nowrap
 :set laststatus=2
 :set tabstop=4
 :set shiftwidth=4
 :set expandtab
 :set backspace=indent,eol,start

"" Search
set hlsearch
set incsearch
set ignorecase
set smartcase

 " ...

 filetype plugin indent on     " required!
 "
 " Brief help
 " :BundleList          - list configured bundles
 " :BundleInstall(!)    - install(update) bundles
 " :BundleSearch(!) foo - search(or refresh cache first) for foo
 " :BundleClean(!)      - confirm(or auto-approve) removal of unused bundles
 "
 " see :h vundle for more details or wiki for FAQ
 " NOTE: comments after Bundle command are not allowed..
