[[ "$OSTYPE" == darwin* ]] && export BROWSER='open'

[[ -z "$LANG" ]] && export LANG='en_GB.UTF-8'

alias ll='ls -lh'
alias la='ls -alh'

alias gfa='git fetch --all --prune'
alias gst='git status'
alias glt="git for-each-ref --sort='-*authordate' --format='%(*authordate) %(refname:short)' 'refs/tags/'"

