source ~/.zplug/init.zsh

zstyle ':prezto:*:*' case-sensitive 'no'
zstyle ':prezto:*:*' color 'yes'
zplug "modules/environment", from:prezto, as:plugin

zplug "plugins/vi-mode", from:oh-my-zsh, as:plugin

zplug "modules/completion", from:prezto, as:plugin
zplug "modules/history", from:prezto, as:plugin

zplug "plugins/git", from:oh-my-zsh, as:plugin
zplug "plugins/git-extras", from:oh-my-zsh, as:plugin

zplug load

export EDITOR='vim'
export VISUAL="${EDITOR}"
[[ ! $TERM = screen-256color ]] && export TERM='xterm-256color'
