source ~/.zplug/init.zsh

zstyle ':prezto:*:*' case-sensitive 'no'
zstyle ':prezto:*:*' color 'yes'
zplug "modules/environment", from:prezto, as:plugin
zplug "modules/completion", from:prezto, as:plugin
zplug "modules/history", from:prezto, as:plugin
zplug "modules/directory", from:prezto, as:plugin

# search history using up/down 
zplug "modules/history-substring-search", from:prezto, as:plugin
# show sugestions based on history
zplug "modules/autosuggestions", from:prezto, as:plugin
zstyle ':prezto:module:autosuggestions' color 'yes'

zplug "modules/homebrew", from:prezto, as:plugin

#zplug "modules/gnu-utility", from:prezto, as:plugin
#zstyle ':prezto:module:gnu-utility' prefix 'g'

zplug "zsh-users/zsh-history-substring-search", as:plugin

zplug "plugins/vi-mode", from:oh-my-zsh, as:plugin
zplug "plugins/git", from:oh-my-zsh, as:plugin
zplug "plugins/git-extras", from:oh-my-zsh, as:plugin

zplug "plugins/ssh-agent", from:oh-my-zsh, as:plugin

zstyle ':omz:plugins:ssh-agent' agent-forwarding on
zstyle ':omz:plugins:ssh-agent' identities ida_rsa id_ed25519

zplug "plugins/golang", from:oh-my-zsh, as:plugin
zplug "docker/cli", use:contrib/completion/zsh
zplug "docker/compose", use:contrib/completion/zsh

zplug "plugins/kubectl", from:oh-my-zsh, as:plugin
zplug "plugins/kube-ps1", from:oh-my-zsh, as:plugin

zplug "tysonwolker/iterm-tab-colors"
zplug "djui/alias-tips", as:plugin

#zplug 'dracula/zsh', as:theme
zplug "themes/candy", from:oh-my-zsh


# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load

export EDITOR='vim'
export VISUAL="${EDITOR}"
[[ ! $TERM = screen-256color ]] && export TERM='xterm-256color'

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

##############################################################
# Dev tooling
eval "$(hub alias -s)"
export GITHUB_USERNAME="jensraaby"

export GOPATH=~/dev/golang
path=($path $GOPATH/bin)

[[ -s "$HOME/.zshrc.extra" ]] && source "$HOME/.zshrc.extra"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

