#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi



[[ ! $TERM = screen-256color ]] && export TERM='xterm-256color'

# Check for extra stuff to source
[[ -s "$HOME/.zshrc.extra" ]] && source "$HOME/.zshrc.extra"

